### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by kraymitchell** [jeffehobbs/embedresponsively#36]
I couldn't find any other mention of this so I thought I would submit.

I added a video to my website (Joomla) yesterday and it works great everywhere but FireFox. It takes up full width, but in FF the video displays really small. Not really sure what's going on with that but thought I would see if anybody else had this issue or a fix.

thanks!

**Comment by jeffehobbs** [comment]
Cannot reproduce. Not enough info to troubleshoot.

**Comment by nattkua** [comment]
I ran into an issue with a vimeo embed collapsing in Firefox. The .embed-container was a direct child of a div using display:flex. I added a div wrapper using display:block around the .embed-container and that fixed the video. Figured I'd share in case someone else runs into this.

```html
<div class='flex-wrapper'>
  <div class='embed-container'>
    <iframe src='vimeo-link' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
    </div>
</div>
```
<img width="885" alt="flex-wrapper" src="https://cloud.githubusercontent.com/assets/1135948/17626238/097e7a5c-6072-11e6-81bc-4a0a23112354.png">

My fix
```html
<div class='flex-wrapper'>
  <div class="block-wrapper">
    <div class='embed-container'>
     <iframe src='vimeo-link' frameborder='0' webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
     </div>
  </div>
</div>
```
<img width="819" alt="block-wrapper" src="https://cloud.githubusercontent.com/assets/1135948/17626309/561c1f7c-6072-11e6-8059-a5f5c00d8157.png">
