### ISSUE TITLE
Disable Related Youtube videos

### ISSUE THREAD

**Issue by rowby** [jeffehobbs/embedresponsively#39]
HI

Great utility. Would be great if it included an option to disable Related Videos in youtube. I know I can manually add the code, but I am not sure exactly where to place it and what specific parameters to add

rel=0 should turn it off, and I think it needs ?rel-0   but I don't know where to place it.

Thanks!
Rowby

**Comment by djbinary** [comment]
Hello. Did you figure this out? I really need help
Thanks

**Comment by jeffehobbs** [comment]
For greater control over YouTube videos, you'd want to use the YouTube JS API, which is outside the scope of this tool.

**Comment by djbinary** [comment]
Thank you
