### ISSUE TITLE
Allow donations

### ISSUE THREAD

**Issue by rolfen** [jeffehobbs/embedresponsively#49]
Hi,

I would like "to make a statement with my wallet".

You took the time and effort to provide fixes for shortcomings from major, commercial platforms, who really don't have any excuse for offering such a sloppy product.

Vimeo UI have a "responsive" option for the embed code, but the result is pathetic.

First of all, thank you! You made my life easier.

I would like to back this thanks with a donation.

So I am suggesting that this option would be offered on the embedresponsively site.

**Comment by jeffehobbs** [comment]
This is very kind! But charging money or taking donations connote other things, and I'm just happy that people find the site's function useful.  Consider your kind comment payment enough!

**Comment by rolfen** [comment]
Thank you for your answer.
I know that developing and maintaining this solution takes time. Time is a limited resource which can usually be traded against money.
So anyway I remain willing to make a minor contribution should you reconsider your policy in the future.

**Comment by jancassio** [comment]
I share the same feeling of @rolfen you guys did really well here. Congratulations!

@jeffehobbs you and your mates are awesome!

If you guys consider helping someone or need any help, just let me know. You guys deserve a favor :)
